sonar.projectKey=alejandro-alvarez-sonarsource_json-repro
sonar.organization=alejandro-alvarez-sonarsource

sonar.projectName=json-repro
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=.github/**

sonar.json.activate=true
sonar.verbose=true
