sonar.projectKey=sonar-eval_json-repro
sonar.organization=sonar-eval

sonar.projectName=json-repro
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=.github/**

sonar.json.activate=true
sonar.verbose=true
sonar.sca.enabled=false
sonar.scm.disabled=true
sonar.cpd.exclusions=**
sonar.sourceEncoding=UTF-8
